### ISSUE TITLE
Bagfiles for running your code

### ISSUE THREAD

**Issue by gurtajbir** [gonultasbu/diffsteered#1]
Hi, 

Thank you for making your code available. your paper contains a really interesting approach to system identification and control design for the F1Tenth platform. Could you please provide the rosbag files which are referred to in the code? 

Thanks!!

**Comment by gonultasbu** [comment]
Hello, I can upload them in a week or so, would that work for you?

**Comment by gurtajbir** [comment]
Thank you for responding so promptly. I am actually working towards a deadline that's early next week. So, if you could kindly provide a Google Drive/Dropbox etc. link earlier, I would be immensely thankful. If this is possible, I can provide my email. 
Thanks.

**Comment by gonultasbu** [comment]
I'll try to get to it early tomorrow morning, I need to touch base with my coauthor to figure out where the data is stored.

**Comment by gurtajbir** [comment]
Thank you. I really appreciate it.

**Comment by gonultasbu** [comment]
I have added them. Let me know if there are any other issues.
